### ISSUE TITLE
Inference code for vgg

### ISSUE THREAD

**Issue by lusinlu** [mongeoroo/Relevance-CAM#1]
Hi! Thank you for the great work!
In the read.me you mentioned that the script supports vgg inference also, but it seems like it does not work for vgg16 (target layer index out of range, size mismatches in relprop...). Could you please provide working scripts for the vgg architecture.

**Comment by mongeoroo** [comment]
Thank you for your email.
 
I modify my code so that running for VGG16.
 
If any error, please tell me
 
Thanks.
 
Lee
 
-----Original Message-----
From: "Lusine ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-06-18 (금) 18:52:52 (GMT+09:00)
Subject: [mongeoroo/Relevance-CAM] Inference code for vgg (#1)
 
Hi! Thank you for the great work!
In the read.me you mentioned that the script supports vgg inference also, but it seems like it does not work for vgg16 (target layer index out of range, size mismatches in relprop...). Could you please provide working scripts for the vgg architecture.

**Comment by lusinlu** [comment]
Thanks for the fast response!
